export const HousingLocation = [
  {
    id: 1,
    name: "John Doe",
    city: "New York",
    state: "NY",
    photo: "url1",
    availableUnits: 5,
    wifi: true,
    laundry: true,
  },
  {
    id: 2,
    name: "Jane Doe",
    city: "Los Angeles",
    state: "CA",
    photo: "url2",
    availableUnits: 3,
    wifi: false,
    laundry: true,
  },
  {
    id: 3,
    name: "Jim Doe",
    city: "Chicago",
    state: "IL",
    photo: "url3",
    availableUnits: 4,
    wifi: true,
    laundry: false,
  },
];
